# Generated by Django 3.1.4 on 2020-12-19 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0002_auto_20201216_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='demo_link',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='github_link',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
